# Generated by Django 6.0.2 on 2026-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='income_frequency',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('weekly', 'Hebdomadaire'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name='Fréquence du revenu'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Revenu mensuel'),
        ),
    ]
