# Generated by Django 6.0.2 on 2026-02-17 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('type', models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense')], max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminée')], default='completed', max_length=10, verbose_name='Statut')),
                ('date', models.DateTimeField(verbose_name='Date de la transaction')),
                ('icon', models.CharField(default='attach_money', max_length=50, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='transaction_user_id_741359_idx'), models.Index(fields=['wallet', '-date'], name='transaction_wallet__05dd62_idx'), models.Index(fields=['type', '-date'], name='transaction_type_6e8944_idx'), models.Index(fields=['category', '-date'], name='transaction_categor_da82d6_idx')],
            },
        ),
    ]
