# Generated by Django 6.0.2 on 2026-02-17 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0003_alter_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='wallets.wallet', verbose_name='Portefeuille destinataire'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense'), ('transfer', 'Transfert')], max_length=10, verbose_name='Type'),
        ),
    ]
