# Generated by Django 6.0.2 on 2026-02-17 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'objectif")),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant cible')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant actuel')),
                ('deadline', models.DateField(verbose_name='Date limite')),
                ('color', models.CharField(default='blue', max_length=50, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Objectif d'épargne",
                'verbose_name_plural': "Objectifs d'épargne",
                'ordering': ['deadline'],
                'indexes': [models.Index(fields=['user', 'deadline'], name='wallets_sav_user_id_92952a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du compte')),
                ('type', models.CharField(choices=[('checking', 'Compte Courant'), ('savings', 'Compte Épargne'), ('credit', 'Carte de Crédit')], max_length=20, verbose_name='Type de compte')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('color', models.CharField(default='blue', max_length=50, verbose_name='Couleur')),
                ('icon', models.CharField(default='account_balance', max_length=50, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallets_wal_user_id_2059b8_idx')],
            },
        ),
    ]
