# Generated by Django 6.0.2 on 2026-02-17 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la charge')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('periodicity', models.CharField(choices=[('monthly', 'Mensuel'), ('weekly', 'Hebdomadaire'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name='Périodicité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Charge fixe',
                'verbose_name_plural': 'Charges fixes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallets_fix_user_id_1eecea_idx')],
            },
        ),
    ]
