# Generated by Django 6.0.2 on 2026-02-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_fixedexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('checking', 'Compte Courant'), ('savings', 'Compte Épargne'), ('credit', 'Carte de Crédit'), ('investment', 'Investissement'), ('cash', 'Espèces')], max_length=20, verbose_name='Type de compte'),
        ),
    ]
